### ISSUE TITLE
SSPs integrations with OpenRTB

### ISSUE THREAD

**Issue by ivopaunov** [heyAuraDev/adex-validator#374]
## Summary

Research how to integrate the initial Supply-Side Platforms (SSP) list that are provided in https://github.com/AmbireTech/aips/issues/80#issuecomment-1375576153 

The basic idea is to make service that will connect the SSPs through [OpenRTB protocol](https://openrtb.github.io/OpenRTB/) with AdEx Platform as Demand-Side Platform (DSP). This service can be part of [adex-validator](https://github.com/AmbireTech/adex-validator) or [adex-validator-stack-rust](https://github.com/AmbireTech/adex-validator-stack-rust) or standalone.

### Tasks 

- [ ]  Research [SSPs](https://github.com/AmbireTech/aips/issues/80#issuecomment-1375576153) integrations with [OpenRTB](https://openrtb.github.io/OpenRTB/)
- [ ]  Service that will connect AdEx users campaigns through [OpenRTB](https://openrtb.github.io/OpenRTB/). (TODO: Convert to epic.)
- [ ]  Service that will make internal accounting for the spent from users campaigns and billed from SSPs. (TODO: Convert to epic.)
- [ ]  Research fraud protection integration with the SSP-s e.g. https://www.humansecurity.com/

**Comment by ivopaunov** [comment]
We can start with this SSP - https://help.dsp.epom.com/reference/processv25

**Comment by ivopaunov** [comment]
Closed in favour of https://github.com/AmbireTech/adex-bridge/issues/2

It will be part of https://github.com/AmbireTech/adex-bridge
